/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AtomicProductTemplate
 */
export interface AtomicProductTemplate {
    /**
     * 
     * @type {number}
     * @memberof AtomicProductTemplate
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof AtomicProductTemplate
     */
    createdAt?: any;
    /**
     * 
     * @type {Date}
     * @memberof AtomicProductTemplate
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProductTemplate
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProductTemplate
     */
    modifiedBy?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AtomicProductTemplate
     */
    deleted?: any;
    /**
     * 
     * @type {AtomicProductDefinition}
     * @memberof AtomicProductTemplate
     */
    atomicProductDefinition?: any;
    /**
     * 
     * @type {LayerShape}
     * @memberof AtomicProductTemplate
     */
    layerShape?: any;
    /**
     * 
     * @type {number}
     * @memberof AtomicProductTemplate
     */
    layerNumber?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProductTemplate
     */
    title?: any;
}
