/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AtomicProduct
 */
export interface AtomicProduct {
    /**
     * 
     * @type {number}
     * @memberof AtomicProduct
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof AtomicProduct
     */
    createdAt?: any;
    /**
     * 
     * @type {Date}
     * @memberof AtomicProduct
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProduct
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProduct
     */
    modifiedBy?: any;
    /**
     * 
     * @type {boolean}
     * @memberof AtomicProduct
     */
    deleted?: any;
    /**
     * 
     * @type {AtomicProductDefinition}
     * @memberof AtomicProduct
     */
    atomicProductDefinition?: any;
    /**
     * 
     * @type {LayerShape}
     * @memberof AtomicProduct
     */
    layerShape?: any;
    /**
     * 
     * @type {number}
     * @memberof AtomicProduct
     */
    layerNumber?: any;
    /**
     * 
     * @type {Pack}
     * @memberof AtomicProduct
     */
    pack?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProduct
     */
    layerStatus?: AtomicProductLayerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof AtomicProduct
     */
    barcodeFromId?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProduct
     */
    barcodeEndProduct?: any;
    /**
     * 
     * @type {StorageArea}
     * @memberof AtomicProduct
     */
    storageArea?: any;
    /**
     * 
     * @type {string}
     * @memberof AtomicProduct
     */
    status?: AtomicProductStatusEnum;
    /**
     * 
     * @type {ProductionOrder}
     * @memberof AtomicProduct
     */
    productionOrder?: any;
    /**
     * 
     * @type {OperationDiagramData}
     * @memberof AtomicProduct
     */
    operationDiagramData?: any;
}

/**
    * @export
    * @enum {string}
    */
export enum AtomicProductLayerStatusEnum {
    INITIAL = 'INITIAL',
    SUCCESS = 'SUCCESS',
    BROKEN = 'BROKEN',
    ISPARTOFANOTHER = 'IS_PART_OF_ANOTHER',
    ISSEPARATED = 'IS_SEPARATED',
    INSTOCK = 'IN_STOCK',
    DOESNOTEXIST = 'DOES_NOT_EXIST'
}
/**
    * @export
    * @enum {string}
    */
export enum AtomicProductStatusEnum {
    AVAILABLE = 'AVAILABLE',
    RESERVED = 'RESERVED',
    NOTAVAILABLE = 'NOT_AVAILABLE'
}

