/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CalendarFilters
 */
export interface CalendarFilters {
    /**
     * 
     * @type {Date}
     * @memberof CalendarFilters
     */
    startDate?: any;
    /**
     * 
     * @type {Date}
     * @memberof CalendarFilters
     */
    endDate?: any;
}
