/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface GidDto
 */
export interface GidDto {
    /**
     * 
     * @type {number}
     * @memberof GidDto
     */
    type?: any;
    /**
     * 
     * @type {number}
     * @memberof GidDto
     */
    company?: any;
    /**
     * 
     * @type {number}
     * @memberof GidDto
     */
    number?: any;
    /**
     * 
     * @type {number}
     * @memberof GidDto
     */
    counter?: any;
}
