/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface OperationType
 */
export interface OperationType {
    /**
     * 
     * @type {number}
     * @memberof OperationType
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof OperationType
     */
    createdAt?: any;
    /**
     * 
     * @type {Date}
     * @memberof OperationType
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof OperationType
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof OperationType
     */
    modifiedBy?: any;
    /**
     * 
     * @type {boolean}
     * @memberof OperationType
     */
    deleted?: any;
    /**
     * 
     * @type {string}
     * @memberof OperationType
     */
    title?: any;
    /**
     * 
     * @type {Array&lt;AtomicProductDefinition&gt;}
     * @memberof OperationType
     */
    allowedAtomicProductDefinitions?: any;
}
