/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Pageable
 */
export interface Pageable {
    /**
     * 
     * @type {number}
     * @memberof Pageable
     */
    offset?: any;
    /**
     * 
     * @type {Sort}
     * @memberof Pageable
     */
    sort?: any;
    /**
     * 
     * @type {number}
     * @memberof Pageable
     */
    pageNumber?: any;
    /**
     * 
     * @type {number}
     * @memberof Pageable
     */
    pageSize?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Pageable
     */
    unpaged?: any;
    /**
     * 
     * @type {boolean}
     * @memberof Pageable
     */
    paged?: any;
}
