/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PageAtomicOperationBasicDto
 */
export interface PageAtomicOperationBasicDto {
    /**
     * 
     * @type {number}
     * @memberof PageAtomicOperationBasicDto
     */
    totalElements?: any;
    /**
     * 
     * @type {number}
     * @memberof PageAtomicOperationBasicDto
     */
    totalPages?: any;
    /**
     * 
     * @type {number}
     * @memberof PageAtomicOperationBasicDto
     */
    size?: any;
    /**
     * 
     * @type {Array&lt;AtomicOperationBasicDto&gt;}
     * @memberof PageAtomicOperationBasicDto
     */
    content?: any;
    /**
     * 
     * @type {number}
     * @memberof PageAtomicOperationBasicDto
     */
    number?: any;
    /**
     * 
     * @type {Sort}
     * @memberof PageAtomicOperationBasicDto
     */
    sort?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PageAtomicOperationBasicDto
     */
    first?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PageAtomicOperationBasicDto
     */
    last?: any;
    /**
     * 
     * @type {number}
     * @memberof PageAtomicOperationBasicDto
     */
    numberOfElements?: any;
    /**
     * 
     * @type {Pageable}
     * @memberof PageAtomicOperationBasicDto
     */
    pageable?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PageAtomicOperationBasicDto
     */
    empty?: any;
}
