/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface PlacedBoxMl
 */
export interface PlacedBoxMl {
    /**
     * 
     * @type {VectorMl}
     * @memberof PlacedBoxMl
     */
    position?: any;
    /**
     * 
     * @type {VectorMl}
     * @memberof PlacedBoxMl
     */
    size?: any;
    /**
     * 
     * @type {boolean}
     * @memberof PlacedBoxMl
     */
    rotation?: any;
    /**
     * 
     * @type {number}
     * @memberof PlacedBoxMl
     */
    amount?: any;
}
