/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProductWithAmount
 */
export interface ProductWithAmount {
    /**
     * 
     * @type {Gid}
     * @memberof ProductWithAmount
     */
    productGid?: any;
    /**
     * 
     * @type {string}
     * @memberof ProductWithAmount
     */
    productCode?: any;
    /**
     * 
     * @type {string}
     * @memberof ProductWithAmount
     */
    productName?: any;
    /**
     * 
     * @type {number}
     * @memberof ProductWithAmount
     */
    amount?: any;
    /**
     * 
     * @type {string}
     * @memberof ProductWithAmount
     */
    unitOfMeasure?: any;
    /**
     * 
     * @type {string}
     * @memberof ProductWithAmount
     */
    ean?: any;
    /**
     * 
     * @type {string}
     * @memberof ProductWithAmount
     */
    characteristic?: any;
    /**
     * 
     * @type {number}
     * @memberof ProductWithAmount
     */
    elementIndex?: any;
    /**
     * 
     * @type {number}
     * @memberof ProductWithAmount
     */
    position?: any;
    /**
     * 
     * @type {Array&lt;string&gt;}
     * @memberof ProductWithAmount
     */
    serialNumbers?: any;
}
