/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface RectangleShapeBasicDto
 */
export interface RectangleShapeBasicDto {
    /**
     * 
     * @type {number}
     * @memberof RectangleShapeBasicDto
     */
    id?: any;
    /**
     * 
     * @type {number}
     * @memberof RectangleShapeBasicDto
     */
    height?: any;
    /**
     * 
     * @type {number}
     * @memberof RectangleShapeBasicDto
     */
    width?: any;
}
