/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface SelectSolutionRequest
 */
export interface SelectSolutionRequest {
    /**
     * 
     * @type {Array&lt;SurfaceWithPlacedEntities&gt;}
     * @memberof SelectSolutionRequest
     */
    spes?: any;
    /**
     * 
     * @type {{ [key, string]: Array&lt;number&gt;;}}
     * @memberof SelectSolutionRequest
     */
    surfaceToSheetDefIdMap?: any;
}
