/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StorageArea
 */
export interface StorageArea {
    /**
     * 
     * @type {number}
     * @memberof StorageArea
     */
    id?: any;
    /**
     * 
     * @type {Date}
     * @memberof StorageArea
     */
    createdAt?: any;
    /**
     * 
     * @type {Date}
     * @memberof StorageArea
     */
    updatedAt?: any;
    /**
     * 
     * @type {string}
     * @memberof StorageArea
     */
    createdBy?: any;
    /**
     * 
     * @type {string}
     * @memberof StorageArea
     */
    modifiedBy?: any;
    /**
     * 
     * @type {boolean}
     * @memberof StorageArea
     */
    deleted?: any;
    /**
     * 
     * @type {string}
     * @memberof StorageArea
     */
    code?: any;
    /**
     * 
     * @type {Warehouse}
     * @memberof StorageArea
     */
    warehouse?: any;
    /**
     * 
     * @type {Array&lt;AtomicProduct&gt;}
     * @memberof StorageArea
     */
    productList?: any;
}
