/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserMLDto
 */
export interface UserMLDto {
    /**
     * 
     * @type {number}
     * @memberof UserMLDto
     */
    id?: any;
    /**
     * 
     * @type {string}
     * @memberof UserMLDto
     */
    username?: any;
    /**
     * 
     * @type {string}
     * @memberof UserMLDto
     */
    firstName?: any;
    /**
     * 
     * @type {string}
     * @memberof UserMLDto
     */
    lastName?: any;
    /**
     * 
     * @type {string}
     * @memberof UserMLDto
     */
    rfidNumber?: any;
    /**
     * 
     * @type {boolean}
     * @memberof UserMLDto
     */
    active?: any;
}
