/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UserWorkTimeDto
 */
export interface UserWorkTimeDto {
    /**
     * 
     * @type {number}
     * @memberof UserWorkTimeDto
     */
    id?: any;
    /**
     * 
     * @type {UserML}
     * @memberof UserWorkTimeDto
     */
    userML?: any;
    /**
     * 
     * @type {Date}
     * @memberof UserWorkTimeDto
     */
    startWorkTime?: any;
    /**
     * 
     * @type {Date}
     * @memberof UserWorkTimeDto
     */
    endWorkTime?: any;
    /**
     * 
     * @type {string}
     * @memberof UserWorkTimeDto
     */
    endWorkTimeReason?: UserWorkTimeDtoEndWorkTimeReasonEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum UserWorkTimeDtoEndWorkTimeReasonEnum {
    FINISHMACHINECALENDARTASK = 'FINISH_MACHINE_CALENDAR_TASK',
    FINISHWORKDAY = 'FINISH_WORK_DAY',
    MACHINEEMERGENCY = 'MACHINE_EMERGENCY',
    BREAKTIME = 'BREAK_TIME'
}

