/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WarehouseFilters
 */
export interface WarehouseFilters {
    /**
     * 
     * @type {string}
     * @memberof WarehouseFilters
     */
    searchQuery?: any;
    /**
     * 
     * @type {ValueParam}
     * @memberof WarehouseFilters
     */
    searchByTotalAmount?: any;
    /**
     * 
     * @type {ValueParam}
     * @memberof WarehouseFilters
     */
    searchByThickness?: any;
    /**
     * 
     * @type {ValueParam}
     * @memberof WarehouseFilters
     */
    searchByHeight?: any;
    /**
     * 
     * @type {ValueParam}
     * @memberof WarehouseFilters
     */
    searchByWidth?: any;
}
