/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface WorkPlaceDto
 */
export interface WorkPlaceDto {
    /**
     * 
     * @type {number}
     * @memberof WorkPlaceDto
     */
    id?: any;
    /**
     * 
     * @type {MachineDto}
     * @memberof WorkPlaceDto
     */
    machine?: any;
    /**
     * 
     * @type {PrinterDto}
     * @memberof WorkPlaceDto
     */
    printer?: any;
}
