/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AtomicProductParameterTypeBasicDto } from '../models';
import { FailableResourceAtomicProductParameterTypeBasicDto } from '../models';
/**
 * AtomicProductParameterTypeControllerApi - axios parameter creator
 * @export
 */
export const AtomicProductParameterTypeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTyDeleteObject: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling atPrPaTyDeleteObject.');
            }
            const localVarPath = `/api/atomic-product-parameter-type/delete/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTyGetObject: async (id: number, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling atPrPaTyGetObject.');
            }
            const localVarPath = `/api/atomic-product-parameter-type/get/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTyGetObjectList: async (options: any = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/atomic-product-parameter-type/list`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AtomicProductParameterTypeBasicDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTySaveObject: async (body: AtomicProductParameterTypeBasicDto, options: any = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling atPrPaTySaveObject.');
            }
            const localVarPath = `/api/atomic-product-parameter-type/save`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.query) {
                query.set(key, options.query[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AtomicProductParameterTypeControllerApi - functional programming interface
 * @export
 */
export const AtomicProductParameterTypeControllerApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atPrPaTyDeleteObject(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await AtomicProductParameterTypeControllerApiAxiosParamCreator(configuration).atPrPaTyDeleteObject(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atPrPaTyGetObject(id: number, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AtomicProductParameterTypeBasicDto>> {
            const localVarAxiosArgs = await AtomicProductParameterTypeControllerApiAxiosParamCreator(configuration).atPrPaTyGetObject(id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atPrPaTyGetObjectList(options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AtomicProductParameterTypeBasicDto>>> {
            const localVarAxiosArgs = await AtomicProductParameterTypeControllerApiAxiosParamCreator(configuration).atPrPaTyGetObjectList(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {AtomicProductParameterTypeBasicDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async atPrPaTySaveObject(body: AtomicProductParameterTypeBasicDto, options?: any): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FailableResourceAtomicProductParameterTypeBasicDto>> {
            const localVarAxiosArgs = await AtomicProductParameterTypeControllerApiAxiosParamCreator(configuration).atPrPaTySaveObject(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AtomicProductParameterTypeControllerApi - factory interface
 * @export
 */
export const AtomicProductParameterTypeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTyDeleteObject(id: number, options?: any): AxiosPromise<string> {
            return AtomicProductParameterTypeControllerApiFp(configuration).atPrPaTyDeleteObject(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTyGetObject(id: number, options?: any): AxiosPromise<AtomicProductParameterTypeBasicDto> {
            return AtomicProductParameterTypeControllerApiFp(configuration).atPrPaTyGetObject(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTyGetObjectList(options?: any): AxiosPromise<Array<AtomicProductParameterTypeBasicDto>> {
            return AtomicProductParameterTypeControllerApiFp(configuration).atPrPaTyGetObjectList(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AtomicProductParameterTypeBasicDto} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        atPrPaTySaveObject(body: AtomicProductParameterTypeBasicDto, options?: any): AxiosPromise<FailableResourceAtomicProductParameterTypeBasicDto> {
            return AtomicProductParameterTypeControllerApiFp(configuration).atPrPaTySaveObject(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AtomicProductParameterTypeControllerApi - object-oriented interface
 * @export
 * @class AtomicProductParameterTypeControllerApi
 * @extends {BaseAPI}
 */
export class AtomicProductParameterTypeControllerApi extends BaseAPI {
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AtomicProductParameterTypeControllerApi
     */
    public atPrPaTyDeleteObject(id: number, options?: any) {
        return AtomicProductParameterTypeControllerApiFp(this.configuration).atPrPaTyDeleteObject(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AtomicProductParameterTypeControllerApi
     */
    public atPrPaTyGetObject(id: number, options?: any) {
        return AtomicProductParameterTypeControllerApiFp(this.configuration).atPrPaTyGetObject(id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AtomicProductParameterTypeControllerApi
     */
    public atPrPaTyGetObjectList(options?: any) {
        return AtomicProductParameterTypeControllerApiFp(this.configuration).atPrPaTyGetObjectList(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {AtomicProductParameterTypeBasicDto} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AtomicProductParameterTypeControllerApi
     */
    public atPrPaTySaveObject(body: AtomicProductParameterTypeBasicDto, options?: any) {
        return AtomicProductParameterTypeControllerApiFp(this.configuration).atPrPaTySaveObject(body, options).then((request) => request(this.axios, this.basePath));
    }
}
